### ISSUE TITLE
[BUG]: Error in read_geophys on November 24, 2004

### ISSUE THREAD

**Issue by ljlamarche** [amisr/flipchem#9]
The `read_geophys` function fails on November 24, 2004 despite running sucessfully at other times. 
**MWE:**
```
>>> import datetime as dt
>>> import flipchem 
>>> flipchem.read_geophys(dt.datetime(2004,11,24,10,0,0))
Traceback (most recent call last):
  File "/home/llamarche/venvs/py37/lib/python3.7/site-packages/flipchem/geophys.py", line 177, in read_geophys
    F107A = F107A + float(lines2[aa][65:70])
ValueError: could not convert string to float: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/llamarche/venvs/py37/lib/python3.7/site-packages/flipchem/geophys.py", line 180, in read_geophys
    F107A = F107A + float(lines2[aa + 1][65:70])
ValueError: could not convert string to float: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/llamarche/venvs/py37/lib/python3.7/site-packages/flipchem/geophys.py", line 182, in read_geophys
    F107A = F107A + float(lines2[aa - 1][65:70])            
ValueError: could not convert string to float: 
```
I've tried updating the geophysical parameters files and this doesn't seem to have made a difference.  This error does not occur for the same function call on April 11, 2004.
```
>>> flipchem.read_geophys(dt.datetime(2004,4,11,10,0,0))
(88.1, 105.16419753086419, array([10.   ,  5.   , 22.   , 22.   ,  9.   , 34.875, 16.75 ]))
```

**Comment by asreimer** [comment]
Note for future debugging: This is likely an issue with the underlying 2004 geophys_params file found in the "dat" directory.

**Comment by asreimer** [comment]
This is the problem: https://github.com/amisr/flipchem/blob/master/flipchem/dat/2004#L350-L356

**Comment by asreimer** [comment]
This was a problem with the underlying geophys params files that get downloaded by flipchem. Those files are generated by other code. That code has been fixed.

To fix the problem, update your parameter files: https://flipchem.readthedocs.io/en/v2020.2.2/usage.html#geophys-params
